pipeline {
    agent any

    environment {
        ANSIBLE_CONFIG = "${WORKSPACE}/deploy/ansible.cfg"
    }

    parameters {
        choice(
            name: 'environment',
            choices: ['dev', 'staging', 'prod'],
            description: 'Select deployment environment'
        )

        string(
            name: 'branch',
            defaultValue: 'master',
            description: 'Branch to build for ansible-config-mgt'
        )
    }

    stages {

        stage('Initial Cleanup') {
            steps {
                cleanWs()
                checkout scm
            }
        }

        stage('Prepare Dependencies') {
            steps {
                dir('php-todo') {
                    git branch: 'main', url: 'https://github.com/heritageolaleye/php-todo.git'

                    sh '''
                    php -v
                    composer install

                    # Ensure Laravel folders exist
                    mkdir -p storage/framework/{sessions,cache,views}
                    mkdir -p bootstrap/cache
                    chmod -R 775 storage bootstrap/cache

                    # Setup environment
                    cp .env.example .env
                    php artisan key:generate
                    php artisan migrate
                    '''
                }
            }
        }

        stage('Execute Tests') {
            steps {
                dir('php-todo') {
                    sh '''
                    # Update APP_KEY in case it's regenerated
                    APP_KEY=$(php artisan key:generate --show)
                    sed -i "s/^APP_KEY=.*/APP_KEY=$APP_KEY/" .env

                    # Ensure storage/cache folders exist
                    mkdir -p storage/framework/{sessions,cache,views}
                    mkdir -p bootstrap/cache
                    chmod -R 775 storage bootstrap/cache

                    echo "APP_KEY Updated"
                    echo "Running Tests"

                    # Run PHPUnit tests
                    ./vendor/bin/phpunit --log-junit tests/junit.xml
                    '''
                }
            }
        }

        stage('Code Analysis') {
            steps {
                dir('php-todo') {
                    sh '''
                    phploc app/ --log-csv build/logs/phploc.csv
                    '''
                }
            }
        }

        stage('Plot Code Coverage Report') {
            steps {
                dir('php-todo') {
                    // Plot all the phploc metrics as Option 1
                    plot csvFileName: 'plot-phploc.csv', 
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Lines of Code (LOC),Comment Lines of Code (CLOC),Non-Comment Lines of Code (NCLOC),Logical Lines of Code (LLOC)', 
                                      file: 'build/logs/phploc.csv', 
                                      inclusionFlag: 'INCLUDE_BY_STRING', url: '']], 
                         group: 'phploc', numBuilds: '100', style: 'line', 
                         title: 'A - Lines of code', yaxis: 'Lines of Code'

                    plot csvFileName: 'plot-phploc.csv', 
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Directories,Files,Namespaces', 
                                      file: 'build/logs/phploc.csv', 
                                      inclusionFlag: 'INCLUDE_BY_STRING', url: '']], 
                         group: 'phploc', numBuilds: '100', style: 'line', 
                         title: 'B - Structures Containers', yaxis: 'Count'

                    plot csvFileName: 'plot-phploc.csv', 
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Average Class Length (LLOC),Average Method Length (LLOC),Average Function Length (LLOC)', 
                                      file: 'build/logs/phploc.csv', 
                                      inclusionFlag: 'INCLUDE_BY_STRING', url: '']], 
                         group: 'phploc', numBuilds: '100', style: 'line', 
                         title: 'C - Average Length', yaxis: 'Average Lines of Code'

                    plot csvFileName: 'plot-phploc.csv', 
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Cyclomatic Complexity / Lines of Code,Cyclomatic Complexity / Number of Methods', 
                                      file: 'build/logs/phploc.csv', 
                                      inclusionFlag: 'INCLUDE_BY_STRING', url: '']], 
                         group: 'phploc', numBuilds: '100', style: 'line', 
                         title: 'D - Relative Cyclomatic Complexity', yaxis: 'Cyclomatic Complexity by Structure'

                    plot csvFileName: 'plot-phploc.csv', 
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Classes,Abstract Classes,Concrete Classes', 
                                      file: 'build/logs/phploc.csv', 
                                      inclusionFlag: 'INCLUDE_BY_STRING', url: '']], 
                         group: 'phploc', numBuilds: '100', style: 'line', 
                         title: 'E - Types of Classes', yaxis: 'Count'

                    plot csvFileName: 'plot-phploc.csv', 
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Methods,Non-Static Methods,Static Methods,Public Methods,Non-Public Methods', 
                                      file: 'build/logs/phploc.csv', 
                                      inclusionFlag: 'INCLUDE_BY_STRING', url: '']], 
                         group: 'phploc', numBuilds: '100', style: 'line', 
                         title: 'F - Types of Methods', yaxis: 'Count'

                    plot csvFileName: 'plot-phploc.csv', 
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Constants,Global Constants,Class Constants', 
                                      file: 'build/logs/phploc.csv', 
                                      inclusionFlag: 'INCLUDE_BY_STRING', url: '']], 
                         group: 'phploc', numBuilds: '100', style: 'line', 
                         title: 'G - Types of Constants', yaxis: 'Count'

                    plot csvFileName: 'plot-phploc.csv', 
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Test Classes,Test Methods', 
                                      file: 'build/logs/phploc.csv', 
                                      inclusionFlag: 'INCLUDE_BY_STRING', url: '']], 
                         group: 'phploc', numBuilds: '100', style: 'line', 
                         title: 'I - Testing', yaxis: 'Count'

                    plot csvFileName: 'plot-phploc.csv', 
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Logical Lines of Code (LLOC),Classes Length (LLOC),Functions Length (LLOC),LLOC outside functions or classes', 
                                      file: 'build/logs/phploc.csv', 
                                      inclusionFlag: 'INCLUDE_BY_STRING', url: '']], 
                         group: 'phploc', numBuilds: '100', style: 'line', 
                         title: 'AB - Code Structure by Logical Lines of Code', yaxis: 'Logical Lines of Code'

                    plot csvFileName: 'plot-phploc.csv', 
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Functions,Named Functions,Anonymous Functions', 
                                      file: 'build/logs/phploc.csv', 
                                      inclusionFlag: 'INCLUDE_BY_STRING', url: '']], 
                         group: 'phploc', numBuilds: '100', style: 'line', 
                         title: 'H - Types of Functions', yaxis: 'Count'

                    plot csvFileName: 'plot-phploc.csv', 
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Interfaces,Traits,Classes,Methods,Functions,Constants', 
                                      file: 'build/logs/phploc.csv', 
                                      inclusionFlag: 'INCLUDE_BY_STRING', url: '']], 
                         group: 'phploc', numBuilds: '100', style: 'line', 
                         title: 'BB - Structure Objects', yaxis: 'Count'
                }
            }
        }
    }

    post {
        always {
            dir('php-todo') {
                junit 'tests/junit.xml'
            }
        }
    }
}

