---
- name: Install Apache
  become: true
  ansible.builtin.apt:
    name: "apache2"
    state: present

- name: Install Git
  become: true
  ansible.builtin.apt:
    name: "git"
    state: present

- name: Install PHP and required modules
  become: true
  ansible.builtin.apt:
    name:
      - php
      - libapache2-mod-php
      - php-mysql
      - php-cli
      - php-curl
      - php-zip
      - php-mbstring
      - php-xml
    state: present
    update_cache: yes

- name: Enable PHP module in Apache
  become: true
  ansible.builtin.command: a2enmod php*
  args:
    warn: false

- name: Restart Apache to apply PHP configuration
  become: true
  ansible.builtin.service:
    name: apache2
    state: restarted
